name: Docker Tests

on: [push, pull_request]

env:
  env_var: ${{ vars.REDIS_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4     
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-app .
